---
- name: Deploy Docker Container
  hosts: all
  become: yes
  tasks:
    - name: Remove old Docker if exists
      yum:
        name: docker
        state: absent

    - name: Install required packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker repo
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull latest Docker image
      command: docker pull ruqiyataj/img1:latest

    - name: Remove old container if running
      command: docker rm -f myapp
      ignore_errors: yes

    - name: Run new container
      command: docker run -d --name myapp -p 8080:8080 ruqiyataj/img1:latest

        
