---
- hosts: all
  become: yes
  tasks:
    - name: Install Docker if not installed
      yum:
        name: docker
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Stop existing container (if running)
      shell: |
        docker ps -q --filter "publish=8080" | xargs -r docker stop
        docker ps -aq --filter "publish=8080" | xargs -r docker rm
      ignore_errors: yes

    - name: Pull latest Docker image
      shell: docker pull ruqiyataj/img1:latest

    - name: Run new Docker container
      shell: docker run -d -p 8080:8080 ruqiyataj/img1:latest

    - name: Verify deployment
      shell: docker ps
      register: docker_output

    - debug:
        var: docker_output.stdout_lines
