---
- hosts: dev
  become: yes
  tasks:
    - name: Install required packages
      yum:
        name: yum-utils
        state: present

    - name: Add Docker repo
      command: >
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
- name: Stop existing container (if running)
  shell: |
    docker ps -q --filter "publish=8080" | xargs -r docker stop
    docker ps -aq --filter "publish=8080" | xargs -r docker rm
  ignore_errors: yes

- name: Pull and run the Docker image
  shell: |
    docker pull ruqiyataj/img1:latest
    docker run -d -p 8080:8080 ruqiyataj/img1:latest
    - name: Pull and run the Docker image
      shell: |
        docker pull ruqiyataj/img1:latest
        docker run -d -p 8080:8080 ruqiyataj/img1:latest
