--
- hosts: dev
  become: true
  tasks:
    - name: Update yum cache
      yum:
        update_cache: yes

    - name: Install dependencies for Docker
      yum:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      yum_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      yum_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker

    - name: Update yum cache after adding Docker repo
      yum:
        update_cache: yes

    - name: Install Docker
      yum:
        name: docker-ce
        state: present

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install pip for Python 3
     yum:
        name: python3-pip
        state: present

    - name: Install docker Python module
      pip:
        name: docker
        executable: pip3
        extra_args: --break-system-packages

    - name: Start the container
      docker_container:
        name: ansibleappc1
        image: "ruqiyataj/img1:latest"
        state: started
        published_ports:
          - "0.0.0.0:8080:8080"
