---
- hosts: dev
  become: true
  tasks:
    - name: Install required packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - curl
        state: present

    - name: Add Docker repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      yum:
        name: docker-ce
        state: present

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install pip for Python 3
      yum:
        name: python3-pip
        state: present

    - name: Install docker Python module
      pip:
        name: docker
        executable: pip3

    - name: Start the container
      docker_container:
        name: ansibleapp
        image: "ruqiyataj/img1:latest"
        state: started
        published_ports:
          - "0.0.0.0:8080:8080"





